{% set name = "django-filter" %}
{% set version = "2.0.0" %}
{% set sha256 = "8c8b7b6befe08ff14e33c17455a5b15aec4d39df14ff3de1f7e8b4cb0795241f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/carltongibson/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django
    - djangorestframework

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import django_filters; import django_filters.rest_framework"

about:
  home: http://github.com/carltongibson/django-filter/tree/master
  summary: 'Django-filter is a a generic system for filtering Django QuerySets based on user selections'
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://django-filter.readthedocs.io/en/latest/
  dev_url: https://github.com/carltongibson/django-filter

extra:
  recipe-maintainers:
    - kwilcox
