{% set name = "django-filter" %}
{% set version = "1.1.0" %}
{% set sha256 = "2894cb3dbea0a7e0117f9f5fe8e64d356113784b51346e2cd23b49b3fb97e71e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/carltongibson/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - django
    - djangorestframework

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import django_filters; import django_filters.rest_framework"

about:
  home: http://github.com/carltongibson/django-filter/tree/master
  summary: 'Django-filter is a a generic system for filtering Django QuerySets based on user selections'
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://django-filter.readthedocs.io/en/latest/
  dev_url: https://github.com/carltongibson/django-filter

extra:
  recipe-maintainers:
    - kwilcox
