travis:
  secure:
    BINSTAR_TOKEN: SWLcj70VsVbyjl12ifsZc+X1nds9jnR4m/R6SR2uqdTazD4xO/S9akOc4OdHMdjYOuOQ1fQXg5mP8wsFYfvxrMFn4tzEGOQW+npEcrXdfrghwYr9ptPYRP9xuWFvou9mDmjtOrMInM6ssXVfNC2UgHzH9hcR1O1Yvg975l/qjHeTVl8ESnt/MrkNDSQe+EPGF0CLUaZruPlIvOWgLhO3UF3/55VWzCANhbY7yBrZcuwV1gXNhK1wIS2MCQz7Ge10irnsYrO0+5vtQGATaRGMrIsmHGBHCUrp0/WZRjsJhqvLus5kGZzBNfK8aglRVucBLEHb8imeRhVNJik4AvT3A9T5/5Ef2n4Byz5X8y/BqdsQO5u2bQwfWFwXn7yLCu0z1CH5pwFbVDBcTIWUGm0aSUTDen/BW5N0albQityFlcIHHvCtkug78K4NDIVKuMZBopoxUF3t55obmlWs82SSZH058ewSNMt5gA0GHz1dFSkjuAtNT0wxUwlN5/9Y3LPcUeCcA91fOptsmycuJ6q8F1uTxlpEV4TwCeSr6AVzV08PjA+ZZLu92Wh5+Rv7Mmy+Ia7DHil2tHsElsUJhBW47T+RdU4ECbVrGYQnJcqdj13W1wUEs4lfD/5pfBgZEJ6DpNlf/Rqf+XJkHtDx2FPkv2Zh7UP3LeA9w6vqJKBiwfU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
