travis:
  secure:
    BINSTAR_TOKEN: YwJy5+6ln3uIzMmWtZcb3CQtSAZnwmHukCpBAl9hQylYBuRzu2xe4/2Z/tL/bmjM7wIZGyLYFApHSV+eyKyI+ykNbrVHZnxVObpL34vifiwgXGPzyPw34YWj6b6+uugKWcwyJrdhjvMkRyJm3STflHvY+vvuMJE+/7HGJH8PqgbX5IAnJ245vZ9vwetCYEbAlCfi/ZcN3eZDgMpSjco68V22e0H1cBPh3zliOcm4mhJ7rSFzKa/KK3AShQ4ETNOFf36sQ4XF8k1nv0HA5v4toVs4aN+IzwV9QeDfEwp0HCkhSsG1B2jO0e2pGE7ZmIoeW7VChqMyaZ2Bc3Enj/OMzi7peCE+8jSTvIZeaIELVVafvCyI8EjAMLz6AzsbgsPhTmT8ym/j59nNflA6iIMnEusRjxvEoqsCrm9ozUFAINrAjfhBJvgJv5FknvZgtjKSrdi2mrbO8YOwHNYXKXy9RfQBiQQNNtnsAGnm3lqBFydspaalCDjjCOmIfOBp3smiZNA3eKQaCzyu2nNiQMBXtlGbpPmxmOa5a5GEtrMuOXRyKnTe5GsOeYd0ePuHswXU3oRrMZhjzNig4BKAo22xW9sSBKxImkbdkJGAtmcHulKXsDOtQ9SGq1CkCJCEfcBKZZqLCkW6uQXg0CCnRUxmJhsS8g8show5ElpWdBY+njM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
